### ISSUE TITLE
Python: Instructions for updating python/docs/?

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#1]
I'm making checksum changes that cause `pytest` to fail when checking examples in the docs. What are the commands for updating `python/docs/`?

**Comment by BjornFJohansson** [comment]
`make html` in the docs folder should do it.

**Comment by BjornFJohansson** [comment]
also 

`pip install sphinx numpydoc sphinx-autobuild sphinx-rtd-theme `

to get it going

**Comment by HenrikBengtsson** [comment]
I've updated the Makefile accordingly, cf. commit cd46a0b99.
