### ISSUE TITLE
Rollback of breaking commits

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#11]
Commit 59704f9 broke the package, resulting in lots of check errors. That commit had several different updates at once, which makes it hard to track down the exact cause.  After this commit, there were attempts to fix it, which I think makes it even harder to narrow in on the problem.  We should always aim at having the state of the main branch checking out with all OK, except for very temporary mistakes.

Because of this, I decided to move those commits to their own branch (https://github.com/seguid/seguid-python/tree/bj), and rollback them back from the main branch.  

# Details on the rollback

```sh
$ git log --oneline
cd46a0b (HEAD -> main, origin/main, origin/HEAD) Update 'make docs' and add 'make docs-install-deps' [#1]
7200ae3 fix toml
1b3895d updated docstrings
cd83f25 slighly better doc, ldseguid docstring has wrong format
59704f9 merge __init__.py
6f402d0 Merge branch 'main' of github.com:seguid/seguid-python
afbf940 Alphabets: promote 'U' and 'O' to the main protein alphabet
...
```
```sh
git revert --no-commit 7200ae3
git revert --no-commit 1b3895d
git revert --no-commit cd83f25
git revert --no-commit 59704f9
```

# Results

After the rollback, the package checks all OK again.

**Comment by BjornFJohansson** [comment]
bj branch: added gitignore for python, removed dynamic versioning by copying the pyproject toml from main branch, removed docs folder. 3f2c117c8333110a8273fbea20d0654b5e0cf36d passes the tests
