### ISSUE TITLE
API: Make seguid.config and seguid.reprutils internal functions

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#13]
The docs (<https://seguid-python.seguid.org/>) list internal functions:

* seguid.config.set_min_rotation(which)[[source]](https://seguid-python.seguid.org/_modules/seguid/config.html#set_min_rotation)

* seguid.reprutils.is_staggered(watson, crick)[[source]](https://seguid-python.seguid.org/_modules/seguid/reprutils.html#is_staggered)

* seguid.reprutils.escape_sequence_spec(spec)[[source]](https://seguid-python.seguid.org/_modules/seguid/reprutils.html#escape_sequence_spec)

* seguid.reprutils.parse_sequence_string(spec: [str](https://docs.python.org/3.8/library/stdtypes.html#str)) → [str](https://docs.python.org/3.8/library/stdtypes.html#str)[[source]](https://seguid-python.seguid.org/_modules/seguid/reprutils.html#parse_sequence_string)

**Comment by BjornFJohansson** [comment]
done!
