### ISSUE TITLE
PyPi release?

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#15]
How far are we from a PyPi release?

**Comment by BjornFJohansson** [comment]
We have one: 
https://pypi.org/project/seguid

You need a pypi user name to be a collaborator or co-owner.

and/or we can use pypi token for uploads from gh action:

I have created a token.

**Comment by BjornFJohansson** [comment]
I can make a release now, but I have only one chance at a version 0.1.0. Pypi will not permit reusing version numbers.
The Python version number is set exclusively in the pyproject.toml file. The "Build for PyPi" action can be run manually to build and publish to PyPi.

**Comment by HenrikBengtsson** [comment]
Let's fix #17 first

**Comment by HenrikBengtsson** [comment]
> You need a pypi user name to be a collaborator or co-owner.

My PyPi username is 'henrikb'.

**Comment by BjornFJohansson** [comment]
sent invite from PyPI
