### ISSUE TITLE
DOCS: More things to be fixed

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#18]
Skimmed through https://seguid-python.seguid.org/ on my phone and found typos, legacy notations and a few other things. I just copy-and-pasted the sentences that I spotted to be fixed below. 

* [x] SEGUID checksum for single stranded linear DNA (slSEGUID).

* [x] The base64.urlsafe_b64encode from the Python standard libary is used.

* [x] See _tables module for details.

* [x] Only defined for circular single-stranded sequences.

* [x] SEGUID checksum for double stranded linear DNA (ldseguid)

* [x] Calculates the ldseguid checksum for a dsDNA sequence defined by two strings representing the upper (Watson) and the complementary (Crick) DNA strands. Optional ssDNA regions in the ends are indicated by a dash “-” in either strand. Watson and Crick strands are always equal in length

* [x] SEGUID checksum for double stranded circular DNA (dcseguid).  The dcseguid is the slseguid checksum calculated for the lexicographically smallest string rotation of a dsDNA sequence. Only defined for circular sequences.

**Comment by HenrikBengtsson** [comment]
Could probably also use bold and italic for some words and sentences, which is straightforwad in reStructure, cf. https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by HenrikBengtsson** [comment]
Regarding the new "introduction" on https://seguid-python.seguid.org/:

* [x] Headers must not end with colons; e.g. right now 'Single-stranded DNA examples:'
* [x] 'pypi' -> 'PyPi'

Miscellaneous:

* [x] 'OBSOLETE, use lsseguid() instead unless for a specific reason.' -> '_Warning_: `seguid()` (obsolete) is superseded by `lsseguid()` (recommended).'

**Comment by HenrikBengtsson** [comment]
Example in "Introduction" in 

Is the following in <https://seguid-python.seguid.org/>:

```
Out[2]: ...
```

from Jupyter, VSCode, or similar?  If so, I think it should be updated to look like a vanilla Python prompt.

**Comment by HenrikBengtsson** [comment]
From a very quick read-through, I spotted:

* [x] Section 'Module contents':  In the table, we don't use "lsSEGUID", etc. in the manuscript or anywhere else.  AFAICT, it's only in that table that is used. I say, spell it out.
* [x] Section 'Module contents': `seguid.seguid()`
* [x] Section 'Module contents': The format/style of the 2006 reference under 'References' in Section 'Module contents' is not the same as in Section 'Reference' above.
* [x] Section 'Module contents': Non-formatted occurrences of 'csseguid'
* [x] Help for 'seguid.csseguid': There is a link to [`lsseguid()`](https://seguid-python.seguid.org/#seguid.lsseguid).  Is that easy to obtain? If so, I think we should use it for all occurrences for the SEGUID functions.

Then I think there are also some standalone sentences that should be merged in the same paragraph.

**Comment by BjornFJohansson** [comment]
Should all be solved in ddb6879

**Comment by BjornFJohansson** [comment]
Anything left todo here?

**Comment by HenrikBengtsson** [comment]
LGTM.  I made a few more tweaks here and there.
