### ISSUE TITLE
DOCS: Reference our manuscript

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#19]
Add reference to SEGUID v2 using citation info as on https://www.seguid.org/publications.html

See https://seguid-r.seguid.org/reference/seguid.html for an example.

**Comment by BjornFJohansson** [comment]
Much improved: 1dc2104 

https://seguid-python.seguid.org/#seguid-v2-checksums-for-linear-circular-single-and-double-stranded-biological-sequences

**Comment by HenrikBengtsson** [comment]
Agree. Very nice with the new introduction.

Regarding _this_ issue, I think "(Humberto et al., 2024)" should be added in several places.

**Comment by HenrikBengtsson** [comment]
I now see how you might have misunderstood this issue. I pointed to <https://seguid-r.seguid.org/reference/seguid.html> for an example of:

"Functions for calculating sequence checksums for linear, circular, single- and double-stranded sequences based on either the original SEGUID (SEGUID v1) algorithm (Babnigg & Giometti, 2006) or the SEGUID v2 algorithm (Pereira et al., 2024)."

which meant to illustrate "(Babnigg & Giometti, 2006)" and "(Pereira et al., 2024)".  The "introduction" is just how R automatically gathers the documents in this case, so that was not the point.

**Comment by BjornFJohansson** [comment]
Should be "Pereira et al., 2024"

**Comment by HenrikBengtsson** [comment]
> Should be "Pereira et al., 2024"

Isn't that what I use?

**Comment by HenrikBengtsson** [comment]
Oh, I see I wrote

> Regarding this issue, I think "(Humberto et al., 2024)" should be added in several places.

in one of my comments above. I meant "Pereira et al., 2024" and that's what I use everywhere in R, etc.
