### ISSUE TITLE
Python: Documentation suggests seguid.chksum.seguid, but it should be seguid.seguid

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#2]
How we name the `seguid/*.py` files should be considered internal, and should _not_ be reflected externally.  For instance, https://seguid.readthedocs.io/en/latest/?badge=latest mentions:

```
 seguid.chksum.seguid(seq: str, table: dict = COMPLEMENT_TABLE_DNA) → str
```

The rule of thumb should be that we should be able to rename those `*.py` files whenever we'd like.

The end-users should only know about `seguid.seguid()` etc., e.g. `from seguid import seguid`, `from seguid import slseguid`, ...

**Comment by BjornFJohansson** [comment]
This is now slightly better cd83f25
Still problems with malformed docstrings.

**Comment by BjornFJohansson** [comment]
This should be solved now.
