### ISSUE TITLE
DOCS: Clarify that our SEGUID v1 implementation is conservative relative to the original one

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#20]
I've just added the following to the R documentation:

https://github.com/seguid/seguid-r/commit/a681154ecf8c0cc114a4e90f40bdec4d601e4f6e

I'm aware the Python docs currently says:

https://github.com/seguid/seguid-python/blob/112a2eded9ba03d03208aa54e7ed69b343e60c1c/src/seguid/_chksum.py#L73-L74

but I think it could be clarified further.

This is related to https://github.com/seguid/seguid-tests/issues/6.

**Comment by BjornFJohansson** [comment]
294665b
