### ISSUE TITLE
PyPi: Add links to GitHub repo and issue tracker

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#22]

**Comment by BjornFJohansson** [comment]
Added links in pyproject.toml

**Comment by BjornFJohansson** [comment]
new build 0.1.0a1  https://pypi.org/project/seguid/0.1.0a1/

**Comment by HenrikBengtsson** [comment]
Did you see my https://github.com/seguid/seguid-python/commit/e94268754accf36bf8acd4ce0cb104616d420f24#r141025217 comment?

**Comment by HenrikBengtsson** [comment]
FYI, can Python and pip compare a version `0.1.0a1` to, say, `0.1.0`?  If not, I suggest using only `x.y.z.u.v` version with numeric components.

**Comment by BjornFJohansson** [comment]
I think so. I use https://semver.org

**Comment by BjornFJohansson** [comment]
fixed home page.

**Comment by HenrikBengtsson** [comment]
Add also a "Bug Tracker" link, cf. https://python-poetry.org/docs/pyproject/#urls

**Comment by BjornFJohansson** [comment]
https://pypi.org/project/seguid/0.0.7
