### ISSUE TITLE
Use numeric-only version numbers

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#23]
The [use of non-numeric components](https://github.com/seguid/seguid-python/issues/22#issuecomment-2061847301) in the package version broke the [CLI package test validating the `--version` output](https://github.com/seguid/seguid-tests/blob/36a5531b0e6635f6a36916fa3b760b05914361cd/tests-cli/01.cli-help.bats#L21-L26);

```sh
not ok 2 <CLI call> --version
# (from function `assert_output' in file test_helper/bats-assert/src/assert_output.bash, line 178,
#  in test file 01.cli-help.bats, line 25)
#   `assert_output --regexp "[[:digit:]]+([.][[:digit:]]+)$"' failed
# cli_call: [n=3] python -m seguid
#
# -- regular expression does not match output --
# regexp : [[:digit:]]+([.][[:digit:]]+)$
# output : 0.1.0a1
# --
```

For this reason, and because it's not clear whether `0.1.0a1` comes before or after `0.1.0`, I think it's better to stick with versiont that has numeric-only components.

**Comment by BjornFJohansson** [comment]
I suggest 0.1.0.0 for next python version then?

**Comment by BjornFJohansson** [comment]
6ac9992e0a7bf54b58414e47d3136122ca34f1ff no version 0.06
