### ISSUE TITLE
codecov.io?

### ISSUE THREAD

**Issue by BjornFJohansson** [seguid/seguid-python#24]
codecov.io seems to fail at the moment. Is there a better alternative?

**Comment by HenrikBengtsson** [comment]
> codecov.io seems to fail at the moment. Is there a better alternative?

I noticed that too - it started some week ago. There must be a simple explanation to it - it's just a matter of troubleshooting, and then the fix should be quick (hopefully).

**Comment by BjornFJohansson** [comment]
Seems to have stopped working here https://github.com/seguid/seguid-python/commit/b3b3d3c85b1359b03cf7d7439bcc3f60ac4dc150

**Comment by HenrikBengtsson** [comment]
Fixed in commit 124a467a.
