### ISSUE TITLE
More feedback on and issues with the Python docs

### ISSUE THREAD

**Issue by HenrikBengtsson** [seguid/seguid-python#27]
First paragraph after the table in <https://seguid-python.seguid.org/#seguid-checksums-for-linear-circular-single-and-double-stranded-sequences> says:

"Four functions for calculations of SEGUID v2 checksums for biological sequences with linear or circular topologies and a single of two complementary strands are provided."

That sounds off to me; is it simply that the "of" should be an "or"?

**Comment by HenrikBengtsson** [comment]
BUG: The links under 'Navigation' on <https://seguid-python.seguid.org/> all points to **pydna**.  I guess it's because:

https://github.com/seguid/seguid-python/blob/4a9292c05da93a70e1248c0f69257f29c48e4a21/docs/conf.py#L43-L49

**Comment by BjornFJohansson** [comment]
I agree that it was not a good way to start. 

New:

"Four SEGUID v2 checksum functions for biological sequences with linear or circular topology and a single or two complementary strands."

old:

"Four functions for calculations of SEGUID v2 checksums for biological sequences with linear or circular topologies and a single of two complementary strands are provided."

**Comment by BjornFJohansson** [comment]
859dbe478166ae30e8d0a9f1da820caf6890bff2 should solve this.
