### ISSUE TITLE
Proteins: Support also 'B', 'X', and 'Z'

### ISSUE THREAD

**Issue by gyorgy5635** [seguid/seguid-python#4]
1. Protein and DNA sequences should be converted to upper case prior hashing: seq = seq.upper()
2. On Windows the "\r" might be introduced into sequences and should be replaced prior hashing: seq = seq.replace("\r","") 
3. In the case of protein sequences those amino acids not in the set of standard amino acid codes should be replaced with "X"

**Comment by HenrikBengtsson** [comment]
Thanks for this.

So, for these _core_ packages, we decided on taking a maximum conservative approach and consider everything that is not in the declared alphabet, or one of the reserved symbols, is considered an error.  This lowers the risk for user mistakes and typos slipping through the cracks.  User-friendly features such as automatic converting to upper case, trimming of whitespace, etc. should be taken care of at a higher level, e.g. GUIs.  I'm not sure if you've read the manuscript yet, but this is explained and argued for there.

> 1. Protein and DNA sequences should be converted to upper case prior hashing: seq = seq.upper()

Because of the above, we get an error here by design:

```
>>> lsseguid("str", alphabet = "{protein}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 128, in lsseguid
    _seguid(seq, alphabet=alphabet, encoding=base64.urlsafe_b64encode),
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 46, in _seguid
    assert_in_alphabet(seq, alphabet=set(tablefactory(alphabet).keys()))
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/asserts.py", line 30, in assert_in_alphabet
    raise ValueError(
ValueError: Detected symbols r t s in not in the 'alphabet'
```

A user who wants to take risk, can easily do:

```python
>>> seq = "str"
>>> lsseguid(seq.upper(), alphabet = "{protein}")
'lsseguid=XAE48kAFPm5eumdhCDd6YRadsaw'
```

> 2. On Windows the "\r" might be introduced into sequences and should be replaced prior hashing: seq = seq.replace("\r","")

Similarly to above, `'\r'` is caught as a non-valid symbol;

```python
>>> lsseguid("S\rTR", alphabet = "{protein}")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 128, in lsseguid
    _seguid(seq, alphabet=alphabet, encoding=base64.urlsafe_b64encode),
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/chksum.py", line 46, in _seguid
    assert_in_alphabet(seq, alphabet=set(tablefactory(alphabet).keys()))
  File "/home/henrik/.local/lib/python3.10/site-packages/seguid/asserts.py", line 31, in assert_in_alphabet
    raise ValueError(
ValueError: Detected symbols '\r' in not in the 'alphabet'
```


> 3. In the case of protein sequences those amino acids not in the set of standard amino acid codes should be replaced with "X".

Is this part of some standard?  Do you have a reference or a pointer? Because if this would be changed, it needs to be documented both in the software tools and the manuscript.  Is this catch anything (think all UTF-8 symbols), or just for the letters in the English alphabet?

That said, by the above argument, this feels like something that should be handled "prior" to SEGUID (e.g. in GUIs). If not, there's really no way we can validate the input and protect against user-mistakes.

**Comment by gyorgy5635** [comment]
I agree that a GUI could handle the sequence preparation. In my original SEGUID implementation for proteins I replaced amino acid characters with 'X' that were not part of the standard code. The new SEGUID method probably should be accepting the extended code as described in:

https://iupac.qmul.ac.uk/AminoAcid/A2021.html


One-lettersymbol | Three-lettersymbol | Amino acid
-- | -- | --
A | Ala | alanine
B | Asx | aspartic acid or asparagine
C | Cys | cysteine
D | Asp | aspartic acid
E | Glu | glutamic acid
F | Phe | phenylalanine
G | Gly | glycine
H | His | histidine
I | Ile | isoleucine
K | Lys | lysine
L | Leu | leucine
M | Met | methionine
N | Asn | asparagine
P | Pro | proline
Q | Gln | glutamine
R | Arg | arginine
S | Ser | serine
T | Thr | threonine
U* | Sec | selenocysteine
V | Val | valine
W | Trp | tryptophan
X** | Xaa | unknown or 'other' amino acid
Y | Tyr | tyrosine
Z | Glx | glutamic acid or glutamine (or substances such as4-carboxyglutamic acid and 5-oxoproline thatyield glutamic acid on acid hydrolysis of peptides)

EDIT +4h: I removed some stray HTML code to make the table render correctly /HB

**Comment by HenrikBengtsson** [comment]
Perfect. I'll read up on this, and I'll see how we add support for `X` the best way.

**Comment by HenrikBengtsson** [comment]
In [`alphabet = "{protein}"`](https://github.com/seguid/seguid-python/blob/677aef7d2365b7a728f12f1e946bf646fef1d869/src/seguid/tables.py#L64-L83), we only include specific amino acids, and none of the "ambiguous" ones listed in https://github.com/seguid/seguid-python/issues/4#issuecomment-1951394571. That is, it's not only `X`, but also `B` and `Z` that are missing:

One-lettersymbol | Three-lettersymbol | Amino acid
-- | -- | --
B | Asx | aspartic acid or asparagine
X** | Xaa | unknown or 'other' amino acid
Z | Glx | glutamic acid or glutamine (or substances such as4-carboxyglutamic acid and 5-oxoproline that yield glutamic acid on acid hydrolysis of peptides)

For someone to use these right now, they can specify `alphabet = "{protein},B,X,Z"`.

I can see a few alternatives here:

1. Keep `{protein}` as is, and ask user to specify `{protein},B,X,Z` if they need this extended "ambiguous" alphabet
2. Add `B,X,Z` to `{protein}`
3. Add another alphabet `{protein-IUPAC} = {protein},B,X,Z`.

The advantage with providing a minimal `{protein}` alphabet is that it allows users who don't use `B,X,Z` (not sure how common that is) to stay conservative and benefit from the stricter error-validation.

We also have an analogue with `{DNA}` and `{IUPAC}`, where the latter has the extra "ambiguous" DNA letters, which are rarely used these days.  BTW, maybe `{IUPAC}` is not specific enough; maybe it should be called `{DNA-IUPAC}` or something else(?!?).

Again, we only use the concept of an alphabet for validation; it doesn't really have a functional purpose. But I still argue that this validation is most critical, even if it adds some friction to the user.

# References

[1] IUPAC-IUB Commission on Biochemical Nomenclature (CBN), A One-Letter Notation for Amino Acid Sequences, J. Biol. Chem. 243, 3557-3559 (1968) [pdf](https://github.com/seguid/seguid-python/files/14326502/PIIS0021925819341766.pdf)

**Comment by HenrikBengtsson** [comment]
Also `J` for `L` or `I` (https://en.wikipedia.org/wiki/International_Union_of_Pure_and_Applied_Chemistry#Amino_acid_and_nucleotide_base_codes)

**Comment by HenrikBengtsson** [comment]
Added "Ambiguous protein" alphabet to the manuscript, analogously to the "Ambiguous DNA" and "Ambiguous RNA" alphabets.  They are specified as `"{protein-IUPAC}"`, `"{DNA-IUPAC}"`, and `"{RNA-IUPAC}"` in all implementations.
