### ISSUE TITLE
Overhang parameter required

### ISSUE THREAD

**Issue by louisabraham** [seguid/seguid-python#6]
```
>>> ldseguid("AT", "AT")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ldseguid() missing 1 required positional argument: 'overhang'
```

**Comment by HenrikBengtsson** [comment]
You appear to be using an old version here. The use of `overhang` parameter was dropped in:

```sh
$ git log --grep overhang
commit 975f74e5b2f60b0ab610a0b9dc697ad1ef29edad
Author: Henrik Bengtsson <henrik.bengtsson@gmail.com>
Date:   Sun Feb 11 17:57:12 2024 -0800

    Python: Drop argument 'overhang' from ldseguid() [#73]
```

**Comment by louisabraham** [comment]
I see! we should push the latest version to PyPI

**Comment by HenrikBengtsson** [comment]
> I see! we should push the latest version to PyPI

Ideally, we should just have had a "don't use" stub on PyPi until we know that SEGUID v2 is final and stable; my main concern all this time has been there are user out there who might have start producing checksums that will no longer be correct. At least the prefixes of the PyPi version are different.

So, we should hold back push an update until we reached milestone 1.0 (= SEGUID v2 is finalized and we don't believe the API or the algorithm will change anymore).
